In [65]:
import pandas as pd
import numpy as np

In [66]:
bed_path = "data/FlowSedimentData.xlsx"
df = pd.read_excel(bed_path, sheet_name="Sediment Data",skiprows=2, header=None)

In [67]:
# 不同区域的河床材料模板
BedTemplate = dict(zip(df.iloc[:3, 2:4].iloc[:, 0], df.iloc[:3, 2:4].iloc[:, 1]))
BedTemplate

{'河岸（Banks）': 'Sands',
 '河道（channel）': 'MainChannel',
 '岛屿（Island）': 'IslandLayers'}

In [73]:
# 床沙级配
BedGradation = df.iloc[6:27, 1:6].replace({np.nan: 0})
BedGradation.columns = BedGradation.iloc[0]
BedGradation = BedGradation.iloc[1:].reset_index(drop=True)
BedGradation

6  Class diam (mm) Sands（% Finer） MainChannel（% Finer） Gravel（% Finer）
0   Clay     0.004              0                    0               0
1    VFM     0.008              0                    0               0
2     FM     0.016              0                    0               0
3     MM     0.032              0                    0               0
4     CM    0.0625              0                    0               0
5    VFS     0.125              0                    0               0
6     FS      0.25            5.8                    5               0
7     MS       0.5           41.6                   10               0
8     CS         1           74.4                   20               0
9    VCS         2           83.7                   30             5.8
10   VFG         4           87.9                   50            41.6
11    FG         8             95                   70            74.4
12    MG        16            100                   80            83.7
13    CG        32              0                   90            87.9
14   VCG        64              0                   95              95
15    SC       128              0                  100             100
16    LC       256              0                    0               0
17    SB       512              0                    0               0
18    MB      1024              0                    0               0
19    LB      2048              0                    0               0

In [74]:
# 分层结构
GradationLayers = df.iloc[27:, 1:4].ffill(axis=0)
GradationLayers.columns = GradationLayers.iloc[0]
GradationLayers = GradationLayers.iloc[1:].reset_index(drop=True)
GradationLayers

27        Layers Layer Thickness Layer Gradation Template
0   IslandLayers               2                     Sand
1   IslandLayers               3                     Sand
2     SandLayers             0.1                   Gravel
3     SandLayers               3                     Sand
4     SandLayers               1     Non-erodible surface